import { useState } from "react";
import type { Finding } from "../lib/types";
import DiffView from "./DiffView";

interface Props {
  findings: Finding[];
  title: string;
}

function shortBase(p: string) {
  return p.split("/").pop() ?? p;
}

export default function FindingsPanel({ findings, title }: Props) {
  const [openId, setOpenId] = useState<string | null>(null);

  return (
    <div>
      <div className="findings-head">
        <h2>{title}</h2>
        <span className="count">{findings.length} shown</span>
      </div>

      {findings.length === 0 ? (
        <div className="empty">Nothing here yet — try clearing a filter.</div>
      ) : (
        <div className="flist">
          {findings.map(f => {
            const open = openId === f.id;
            return (
              <div key={f.id} className={`frow${open ? " open" : ""}`} style={{ ["--sev-color" as any]: `var(--${f.severity})` }}>
                <button className="frow-head" onClick={() => setOpenId(open ? null : f.id)}>
                  <span className={`sev-badge ${f.severity}`}>{f.severity}</span>
                  <span className="fid">{f.id}</span>
                  <span className="fissue">{f.issue}</span>
                  <span className="floc">{shortBase(f.file)} (line {f.line})</span>
                  <span className="chev">▸</span>
                </button>
                {open && (
                  <div className="fbody-inner">
                    <p>{f.description}</p>
                    {f.patch ? (
                      <>
                        <div className="fixblock">
                          <span className="label">
                            {f.patch.generatedByBob ? "Patch generated by Bob" : "Suggested fix"}
                          </span>
                          {f.fix}
                        </div>
                        <DiffView before={f.patch.before} after={f.patch.after} />
                      </>
                    ) : (
                      <div className="fixblock">
                        <span className="label">Suggested fix</span>
                        {f.fix}
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
